/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ukk.waka;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ASUS
 */
public class RiwayatWaka1 extends javax.swing.JFrame {

    /**
     * Creates new form RiwayatAspirasi
     */
   
    PreparedStatement pst = null;
   
    public RiwayatWaka1() {
        initComponents();
        load_riwayat();
    
    }
    
    public void load_riwayat() {
    DefaultTableModel model = new DefaultTableModel();

    try {
        String sql = "SELECT * FROM pengaduan "
                   + "WHERE status IS NOT NULL AND status != '' "
                   + "ORDER BY tgl_pengaduan ASC";

        Connection conn = Koneksi.Koneksi.KoneksiDB();
        Statement stm = conn.createStatement();
        ResultSet res = stm.executeQuery(sql);

        // 🔥 Ambil metadata kolom otomatis
        java.sql.ResultSetMetaData meta = res.getMetaData();
        int jumlahKolom = meta.getColumnCount();

        // 🔥 Tambahkan nama kolom otomatis
        for (int i = 1; i <= jumlahKolom; i++) {
            model.addColumn(meta.getColumnName(i));
        }

        // 🔥 Isi data otomatis
        while (res.next()) {
            Object[] row = new Object[jumlahKolom];
            for (int i = 0; i < jumlahKolom; i++) {
                row[i] = res.getObject(i + 1);
            }
            model.addRow(row);
        }

        tb_riwayat.setModel(model);
        lbl_total.setText("TOTAL DATA: " + tb_riwayat.getRowCount() + " pengaduan");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal Load Data: " + e.getMessage());
    }

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_riwayat = new javax.swing.JTable();
        txt_cari_nama = new javax.swing.JTextField();
        cb_kategori = new javax.swing.JComboBox<>();
        tgl_dari = new com.toedter.calendar.JDateChooser();
        tgl_sampai = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_filter = new javax.swing.JButton();
        lbl_total = new javax.swing.JLabel();
        btn_detail = new javax.swing.JButton();
        btn_cetak_filter = new javax.swing.JButton();
        btn_cetak_all = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tb_riwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Tanggal", "Nama ", "Isi Aspirasi", "Kategori", "Status"
            }
        ));
        jScrollPane1.setViewportView(tb_riwayat);

        txt_cari_nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cari_namaKeyReleased(evt);
            }
        });

        cb_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nama", "Kategori" }));

        jLabel1.setText("Dari");

        jLabel2.setText("Sampai");

        btn_filter.setText("Filter");
        btn_filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_filterActionPerformed(evt);
            }
        });

        lbl_total.setText("TOTAL DATA :");

        btn_detail.setText("Detail");
        btn_detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_detailActionPerformed(evt);
            }
        });

        btn_cetak_filter.setText("Cetak Filter");
        btn_cetak_filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetak_filterActionPerformed(evt);
            }
        });

        btn_cetak_all.setText("Cetak Semua");
        btn_cetak_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetak_allActionPerformed(evt);
            }
        });

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel3.setText("RIWAYAT WAKA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tgl_dari, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(tgl_sampai, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(btn_filter))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(127, 127, 127))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_cari_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cb_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lbl_total)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_detail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_cetak_filter)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_cetak_all)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_cari_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tgl_dari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(tgl_sampai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cb_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_filter)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_total)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_detail)
                    .addComponent(btn_cetak_filter)
                    .addComponent(btn_cetak_all)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_filterActionPerformed
        // TODO add your handling code here :                                                                                  
    if (tgl_dari.getDate() == null || tgl_sampai.getDate() == null) {
        JOptionPane.showMessageDialog(this, "Silakan pilih rentang tanggal!");
        return;
    }

    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID");
    model.addColumn("NIK");
    model.addColumn("tgl_pengaduan");
    model.addColumn("Isi Laporan");
    model.addColumn("Nama"); // Tambahkan ini
    model.addColumn("Foto");
    model.addColumn("Lokasi");
    model.addColumn("Kategori");
    model.addColumn("Status");
    

    try {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dari = sdf.format(tgl_dari.getDate());
        String sampai = sdf.format(tgl_sampai.getDate());

        int no = 1;
        String sql = "SELECT * FROM pengaduan WHERE tgl_pengaduan BETWEEN ? AND ? ORDER BY tgl_pengaduan ASC";
        
        java.sql.Connection conn = Koneksi.Koneksi.KoneksiDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, dari);
        pst.setString(2, sampai);
        java.sql.ResultSet res = pst.executeQuery();

        while (res.next()) {
            model.addRow(new Object[]{
                no++, 
                res.getString("id_pengaduan"), 
                res.getString("nik"), 
                res.getString("tgl_pengaduan"), 
                res.getString("isi_laporan"), 
                res.getString("nama"),
                res.getString("foto"),
                res.getString("lokasi"),
                res.getString("Kategori"),
                res.getString("status")
            });
        }
        tb_riwayat.setModel(model);
        lbl_total.setText("TOTAL DATA FILTER: " + tb_riwayat.getRowCount() + " Pengaduan");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal filter: " + e.getMessage());
    }

    }//GEN-LAST:event_btn_filterActionPerformed

    private void btn_cetak_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetak_filterActionPerformed
        // TODO add your handling code here:                                                                                               
    try {
        if (tgl_dari.getDate() == null || tgl_sampai.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Pilih tanggal filter dulu sebelum cetak!");
            return;
        }
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        java.util.HashMap parameter = new java.util.HashMap();
        
        parameter.put("tgl_awal", sdf.format(tgl_dari.getDate()));
        parameter.put("tgl_akhir", sdf.format(tgl_sampai.getDate()));

        // Lokasi file pastikan huruf besar kecilnya sama dengan di folder project
        java.io.File reportFile = new java.io.File("src/report/laporan_riwayat.jasper");
        
        // PERBAIKAN: Menggunakan ukk.koneksiDB.getKoneksi()
        java.sql.Connection conn = Koneksi.Koneksi.KoneksiDB();
        
        JasperPrint jp = JasperFillManager.fillReport(reportFile.getPath(), parameter, conn);
        JasperViewer.viewReport(jp, false);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Cetak Gagal: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_cetak_filterActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
    txt_cari_nama.setText("");        // Mengosongkan kolom cari
    tgl_dari.setDate(null);           // Mengosongkan filter tanggal awal
    tgl_sampai.setDate(null);         // Mengosongkan filter tanggal akhir
    cb_kategori.setSelectedIndex(0);  // Mengembalikan combobox ke pilihan pertama
    load_riwayat();                   // Memanggil kembali semua data dari database

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_detailActionPerformed
        // TODO add your handling code here:                                                                                                                              
    int row = tb_riwayat.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data dulu!");
        return;
    }

    try {

        StringBuilder detail = new StringBuilder();
        String pathFoto = null;

        detail.append("DETAIL DATA PENGADUAN\n");
        detail.append("====================================\n");

        for (int i = 0; i < tb_riwayat.getColumnCount(); i++) {

            String namaKolom = tb_riwayat.getColumnName(i);
            Object value = tb_riwayat.getValueAt(row, i);

            if (namaKolom.equalsIgnoreCase("foto")) {
                pathFoto = value == null ? null : value.toString();
            } else {
                detail.append(namaKolom)
                      .append(" : ")
                      .append(value == null ? "-" : value.toString())
                      .append("\n");
            }
        }

        detail.append("====================================");

        // ================= PANEL UTAMA =================
        JPanel panelUtama = new JPanel(new BorderLayout(20, 10));

        // ================= TEXT DETAIL =================
        JTextArea textArea = new JTextArea(detail.toString());
        textArea.setEditable(false);
        textArea.setLineWrap(true);
        textArea.setWrapStyleWord(true);

        JScrollPane scrollText = new JScrollPane(textArea);
        scrollText.setPreferredSize(new Dimension(350, 250));

        panelUtama.add(scrollText, BorderLayout.CENTER);

        // ================= FOTO =================
        if (pathFoto != null && !pathFoto.isEmpty()) {

            java.io.File file = new java.io.File(pathFoto);

            if (file.exists()) {

                ImageIcon icon = new ImageIcon(pathFoto);

                Image img = icon.getImage().getScaledInstance(250, 250, Image.SCALE_SMOOTH);
                JLabel lblFoto = new JLabel(new ImageIcon(img));
                lblFoto.setHorizontalAlignment(JLabel.CENTER);

                panelUtama.add(lblFoto, BorderLayout.EAST);

            } else {
                panelUtama.add(new JLabel("Foto tidak ditemukan"), BorderLayout.EAST);
            }
        }

        JOptionPane.showMessageDialog(this, panelUtama,
                "Detail Pengaduan",
                JOptionPane.PLAIN_MESSAGE);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
                "Gagal tampil detail: " + e.getMessage());
    }

    }//GEN-LAST:event_btn_detailActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:                                        
    // 1. Memanggil objek Menu Admin
    // Sesuaikan nama class dengan file menu utama Anda (berdasarkan gambar: menuAdmin)
    ukk.menu.menuWaka waka = new ukk.menu.menuWaka();
    
    // 2. Menampilkan Menu waka
    waka.setVisible(true);
    
    // 3. Menutup halaman Riwayat Aspirasi saat ini
    this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_cetak_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetak_allActionPerformed
        // TODO add your handling code here:                                            
     // 1. Pastikan koneksi tidak null
        Connection conn = Koneksi.Koneksi.KoneksiDB(); 
        if (conn == null) {
            JOptionPane.showMessageDialog(null, "Koneksi Database Gagal!");
            return;
        }
        
    String sql = "SELECT\n" +
"     aspirasi.`id_aspirasi` AS aspirasi_id_aspirasi,\n" +
"     aspirasi.`nik` AS aspirasi_nik,\n" +
"     aspirasi.`nama` AS aspirasi_nama,\n" +
"     aspirasi.`isi_aspirasi` AS aspirasi_isi_aspirasi,\n" +
"     aspirasi.`status` AS aspirasi_status,\n" +
"     aspirasi.`tanggal` AS aspirasi_tanggal\n" + // Kolom feedback dihapus dari sini
"FROM\n" +
"     `aspirasi` aspirasi";
try {
     pst = conn.prepareStatement(sql);   // Buat PreparedStatement dengan query
    ResultSet rp = pst.executeQuery(); 
    JasperPrint jasperPrint;
    JRResultSetDataSource jrRS = new JRResultSetDataSource(rp);
    JasperReport jasperReport = JasperCompileManager.compileReport("D:\\buiza\\ukk\\src\\ukk\\ReportUKK\\laporan_aspirasi.jrxml");
    jasperPrint = JasperFillManager.fillReport(jasperReport, null, jrRS);
    JRViewer aViewer = new JRViewer(jasperPrint);
    JDialog viewer = new JDialog();
    viewer.setTitle(". laporan Report : .");
    viewer.setAlwaysOnTop (true);
    viewer.getContentPane().add(aViewer);
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    viewer.setBounds (0, 0, screenSize.width, screenSize.height);
    viewer.setVisible(true);
}  catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Laporan gak ada: " + e.getMessage());
    e.printStackTrace();
}
    }//GEN-LAST:event_btn_cetak_allActionPerformed

    private void txt_cari_namaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cari_namaKeyReleased
        // TODO add your handling code here:                                        
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("No");
    model.addColumn("ID");
    model.addColumn("NIK");
    model.addColumn("tgl_pengaduan");
    model.addColumn("Isi Laporan");
    model.addColumn("Nama"); // Tambahkan ini
    model.addColumn("Foto");
    model.addColumn("Lokasi");
    model.addColumn("Kategori");
    model.addColumn("Status");

    try {
        String cari = txt_cari_nama.getText();
        // Query tetap sama, mencari dari depan
        String sql = "SELECT * FROM pengaduan WHERE (nama LIKE ? OR kategori LIKE ? OR isi_laporan LIKE ?) ORDER BY tgl_pengaduan ASC";

        java.sql.Connection conn = Koneksi.Koneksi.KoneksiDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, cari + "%"); 
        pst.setString(2, cari + "%"); 
        pst.setString(3, cari + "%"); 
        
        java.sql.ResultSet res = pst.executeQuery();

        int no = 1;
        while (res.next()) {
            model.addRow(new Object[]{
                no++, 
                res.getString("id_pengaduan"), 
                res.getString("nik"), 
                res.getString("tgl_pengaduan"), 
                res.getString("isi_laporan"), 
                res.getString("nama"),
                res.getString("foto"),
                res.getString("lokasi"),
                res.getString("Kategori"),
                res.getString("status")
            });
        }
        tb_riwayat.setModel(model);
        lbl_total.setText("TOTAL HASIL: " + tb_riwayat.getRowCount() + " Pengaduan");

    } catch (Exception e) {
        // Untuk auto-search, sebaiknya tidak pakai JOptionPane error agar tidak mengganggu saat mengetik
        System.out.println("Error search: " + e.getMessage());
    }

    }//GEN-LAST:event_txt_cari_namaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RiwayatWaka1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RiwayatWaka1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RiwayatWaka1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RiwayatWaka1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RiwayatWaka1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cetak_all;
    private javax.swing.JButton btn_cetak_filter;
    private javax.swing.JButton btn_detail;
    private javax.swing.JButton btn_filter;
    private javax.swing.JComboBox<String> cb_kategori;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JTable tb_riwayat;
    private com.toedter.calendar.JDateChooser tgl_dari;
    private com.toedter.calendar.JDateChooser tgl_sampai;
    private javax.swing.JTextField txt_cari_nama;
    // End of variables declaration//GEN-END:variables
}
