/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ukk.waka;

import ukk.pelapor.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.swing.JRViewer;


/**
 *
 * @author dppra
 */
public class verivikasiwaka extends javax.swing.JFrame {

    /**
     * Creates new form registrasi
     */
    
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    String pathFoto = null;

    
   // private final DateFormat dfl = new SimpleDateFormat("dd/MM/yyyy");
    //Calendar hariIni;
   

   private void setTanggalHariIni() {
    jd_tglpengaduan.setDate(new Date());
    jd_tglpengaduan.getDateEditor().setEnabled(false);
    jd_tglpengaduan.getCalendarButton().setEnabled(false);
}
    
    private DefaultTableModel model;
    
    public verivikasiwaka() {
        initComponents();
        setLocationRelativeTo(null);// membuat tengah form
        setTanggalHariIni();
        conn = Koneksi.Koneksi.KoneksiDB(); //javaConnect = nama file || Connection = nama method
        
        
        //memberi penamaan pada judul kolom ; 
        model = new DefaultTableModel();
        jTable1.setModel(model);
        model.addColumn("id pengaduan");
        model.addColumn("nik");
        model.addColumn("nama");
        model.addColumn("Tanggal Pengaduan");
        model.addColumn("Isi Laporan");
        model.addColumn("Foto");
        model.addColumn("Status");
        
        
        getData();//memanggil method getdata
       }
    //menampilkan data kejTabel1
    void getData() {
    model.getDataVector().removeAllElements();
    model.fireTableDataChanged();
       
    
    try {
        //membuat statement pemanggilan data pada table surat_masuk dari database 
        String sql = "select * from pengaduan";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        
        //penelusuran baris pada table surat_masuk dari database
        while (rs.next()) {
            Object[] obj = new Object[7];
            obj[0] = rs.getString("id_pengaduan");
            obj[1] = rs.getString("nik");
            obj[2] = rs.getString("nama");
            obj[3] = rs.getString("tgl_pengaduan");
            obj[4] = rs.getString("isi_laporan");
            obj[5] = rs.getString("foto");
            obj[6] = rs.getString("status");
            
 
            
            model.addRow(obj);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);      
    }
} 
 //menampilkan data dr tabel ke masing-masing komponen cara 2
   void pilihData() {
       int i = jTable1.getSelectedRow();
      // txt_pengaduan.setText(model.getValueAt(i, 0).toString());
//       txt_nik.setText(model.getValueAt(i, 0).toString());
//       txt_nama.setText(model.getValueAt(i, 1).toString());
       
       txt_isi.setText(model.getValueAt(i, 1).toString());
     lbl_foto.setText(model.getValueAt(i, 2).toString());
     
   } 
   
   void bersih() {
       id.setText("");
//       txt_nik.setText("");
//       txt_nama.setText("");
       txt_isi.setText("");
      // txt_status11.setText("");
       
       // HAPUS TANGGAL
        jd_tglpengaduan.setDate(null);
       
        // HAPUS FOTO
       lbl_foto.setIcon(null);
       pathFoto = null;

 
       
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jd_tglpengaduan = new com.toedter.calendar.JDateChooser();
        txt_isi = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cmb_cari = new javax.swing.JComboBox<>();
        txt_cari = new javax.swing.JTextField();
        lbl_foto = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        cmb_status = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pengaduan Masyarakat");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jd_tglpengaduan, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 210, 30));

        txt_isi.setBackground(new java.awt.Color(204, 204, 204));
        txt_isi.setColumns(20);
        txt_isi.setRows(5);
        txt_isi.setBorder(null);
        jPanel1.add(txt_isi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 210, -1));

        jButton3.setText("update");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 50, 20));

        jButton7.setText("exit");
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 50, 20));

        jButton6.setText("cari");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 60, 20));

        jButton2.setText("save");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 50, 20));

        cmb_cari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "NAMA" }));
        cmb_cari.setBorder(null);
        cmb_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_cariActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 90, -1));

        txt_cari.setBorder(null);
        jPanel1.add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 150, 20));

        lbl_foto.setBackground(new java.awt.Color(255, 255, 255));
        lbl_foto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lbl_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 100, 130));

        id.setEditable(false);
        id.setBackground(new java.awt.Color(204, 204, 204));
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 210, 30));

        cmb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "menunggu", "terverifikasi" }));
        cmb_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_statusActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 210, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 480, 170));

        jLabel1.setText("id");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 50, -1));

        jLabel2.setText("tanggal");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel3.setText("isi_pengaduan");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel4.setText("status");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel5.setText("foto");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 954, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_cariActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String sql = "";
            
         model.getDataVector().removeAllElements();
         model.fireTableDataChanged();
         try {
              if (cmb_cari.getSelectedIndex() == 0) {
                    sql = "SELECT * FROM pengaduan where id_pengaduan like '%" + txt_cari.getText() + "%' ";
                    
               }
              if (cmb_cari.getSelectedIndex() == 1) {
                    sql = "SELECT * FROM pengaduan where nik like '%" + txt_cari.getText() + "%' ";
               }
                
              pst = conn.prepareStatement(sql);
              rs = pst.executeQuery();
                
              while (rs.next()) {
                  Object[] obj = new Object[5];
                  obj[0] = rs.getString("id_pengaduan");
                  obj[1] = rs.getString("nik");
                  obj[2] = rs.getString("tgl_pengaduan");
                  obj[3] = rs.getString("isi_laporan");
                 // obj[4] = rs.getString("status");
                    
                    
                  model.addRow(obj);
                }
              
     } catch (Exception e) {
          JOptionPane.showMessageDialog(null, e);
        } 
         // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable1MouseClicked(evt);
        }
       });

        
        int i = jTable1.getSelectedRow(); // Mendapatkan baris yang dipilih
        TableModel model = jTable1.getModel();

        id.setText(model.getValueAt(i, 0).toString());
//        txt_nik.setText(model.getValueAt(i, 1).toString());
//        txt_nama.setText(model.getValueAt(i, 2).toString());
        txt_isi.setText(model.getValueAt(i, 4).toString());
        cmb_status.setSelectedItem(model.getValueAt(i, 6).toString());

        
        // TANGGAL
    try {
        String tanggal = model.getValueAt(i, 3).toString();
        java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(tanggal);
        jd_tglpengaduan.setDate(date);
    } catch (Exception e) {
        e.printStackTrace();
    }

    // ================= FOTO =================
    pathFoto = model.getValueAt(i, 5).toString();

    ImageIcon icon = new ImageIcon(pathFoto);
    Image img = icon.getImage().getScaledInstance(
        lbl_foto.getWidth(),
        lbl_foto.getHeight(),
        Image.SCALE_SMOOTH
    );
    lbl_foto.setIcon(new ImageIcon(img));
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         ukk.menu.menuWaka menuWaka = new ukk.menu.menuWaka();
        menuWaka.setVisible(true);
        this.setVisible(false);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String tampilan="yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal=String.valueOf(fm.format(jd_tglpengaduan.getDate()));
        try {
            String id_pengaduan = id.getText(); // id dari row yang dipilih
            String status = cmb_status.getSelectedItem().toString(); // ambil status dari combobox

            String sql = "UPDATE pengaduan SET status=? WHERE id_pengaduan=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, status);
            pst.setString(2, id_pengaduan);

            pst.executeUpdate(); // executeUpdate lebih tepat untuk update
            JOptionPane.showMessageDialog(null, "UPDATE SUKSES");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                getData();
                bersih();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void cmb_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_statusActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        bersih();
        getData();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(verivikasiwaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(verivikasiwaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(verivikasiwaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(verivikasiwaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new verivikasiwaka().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_cari;
    private javax.swing.JComboBox<String> cmb_status;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser jd_tglpengaduan;
    private javax.swing.JLabel lbl_foto;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextArea txt_isi;
    // End of variables declaration//GEN-END:variables
    
}
