/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ukk.admin;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import java.io.File;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JDialog;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author ASUS
 */
public class Aspirasi1 extends javax.swing.JFrame {

    /**
     * Creates new form Aspirasi1
     */
    
    PreparedStatement pst = null;
    
    public Aspirasi1() {
        initComponents();
        tampilkan_data();
        setTanggalHariIni();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_nik = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_isi = new javax.swing.JTextArea();
        cb_status = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbAspirasi = new javax.swing.JTable();
        txt_cari = new javax.swing.JTextField();
        cb_filter = new javax.swing.JComboBox<>();
        txt_id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btn_refresh = new javax.swing.JButton();
        txt_tanggal = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cb_kategori = new javax.swing.JComboBox<>();
        cb_statusfil = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("ASPIRASI ADMIN");

        jLabel2.setText("NIK / NISN");

        jLabel3.setText("Nama");

        jLabel4.setText("Isi Aspirasi");

        jLabel5.setText("Status");

        txt_nik.setEditable(false);
        txt_nik.setBackground(new java.awt.Color(153, 153, 153));
        txt_nik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nikActionPerformed(evt);
            }
        });

        txt_nama.setEditable(false);
        txt_nama.setBackground(new java.awt.Color(153, 153, 153));
        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });

        txt_isi.setEditable(false);
        txt_isi.setBackground(new java.awt.Color(153, 153, 153));
        txt_isi.setColumns(20);
        txt_isi.setRows(5);
        jScrollPane1.setViewportView(txt_isi);

        cb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "terimakasih", "diterapkan", " " }));
        cb_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_statusActionPerformed(evt);
            }
        });

        tbAspirasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NISN", "Nama", "Tanggal", "Isi Aspirasi", "Status", "Kategori"
            }
        ));
        tbAspirasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAspirasiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbAspirasi);

        txt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariActionPerformed(evt);
            }
        });
        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cariKeyReleased(evt);
            }
        });

        cb_filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "NIK", "NISN", "Nama", "Kategori" }));
        cb_filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_filterActionPerformed(evt);
            }
        });

        txt_id.setEditable(false);
        txt_id.setBackground(new java.awt.Color(153, 153, 153));

        jLabel6.setText("ID");

        btn_refresh.setText("Segarkan");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        txt_tanggal.setBackground(new java.awt.Color(153, 153, 153));

        jLabel7.setText("Tgl Aspirasi");

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_hapus.setText("Keluar");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        jLabel8.setText("Kategori");

        cb_kategori.setForeground(new java.awt.Color(102, 102, 102));
        cb_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hardware PC Lab", "Software & Library", "Jaringan & Internet", "Sarana Ruang Praktik", "Kelistrikan & Kabel" }));

        cb_statusfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "terimakasih", "diterapkan" }));
        cb_statusfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_statusfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(127, 127, 127)
                        .addComponent(txt_cari)
                        .addGap(18, 18, 18)
                        .addComponent(cb_filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cb_statusfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_refresh))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_id)
                                    .addComponent(txt_nik)
                                    .addComponent(txt_nama)
                                    .addComponent(txt_tanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cb_kategori, 0, 239, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_simpan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_hapus))
                                    .addComponent(cb_status, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_refresh)
                            .addComponent(cb_statusfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel6)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_nik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(txt_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_hapus)
                            .addComponent(btn_simpan))))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_filterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_filterActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:                                                                             
  try {
    // 1. Ambil data dari inputan
    String id_aspirasi = txt_id.getText(); 
    String status_baru = cb_status.getSelectedItem().toString();

    // Validasi kalau ID kosong
    if (id_aspirasi.equals("")) {
        JOptionPane.showMessageDialog(this, "Pilih data di tabel dahulu!");
        return;
    }

    // 2. Koneksi ke Database
    java.sql.Connection conn = Koneksi.Koneksi.KoneksiDB();

    // 3. Query Update Status
    String sqlUpdate = "UPDATE aspirasi SET status=? WHERE id_aspirasi=?"; 
    
    java.sql.PreparedStatement pstUp = conn.prepareStatement(sqlUpdate);
    pstUp.setString(1, status_baru); // Mengisi tanda tanya ke-1
    pstUp.setString(2, id_aspirasi); // Mengisi tanda tanya ke-2
    
    int hasil = pstUp.executeUpdate();

    // 4. Cek hasil
    if (hasil > 0) {
        JOptionPane.showMessageDialog(null, "Status berhasil diperbarui!");
        tampilkan_data(); // Panggil fungsi refresh tabel kamu
        bersih();         // Panggil fungsi reset form kamu
    }
    
} catch (Exception e) {
    // Pastikan bagian ini TIDAK berisi "throw new UnsupportedOperationException"
    JOptionPane.showMessageDialog(this, "Gagal Update: " + e.getMessage());
}
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:                                       
   ukk.menu.menuAdmin menu = new ukk.menu.menuAdmin();
    
    // 2. Menampilkan Menu Admin
    menu.setVisible(true);
    
    // 3. Menutup halaman Riwayat Aspirasi saat ini
    this.dispose();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void tbAspirasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAspirasiMouseClicked
        // TODO add your handling code here:                                                                                                                                                                                                                                                                                  
    int i = tbAspirasi.getSelectedRow();
    if (i != -1) {
        txt_id.setText(tbAspirasi.getValueAt(i, 0).toString());
        txt_nik.setText(tbAspirasi.getValueAt(i, 1).toString());
        txt_nama.setText(tbAspirasi.getValueAt(i, 2).toString());
        txt_isi.setText(tbAspirasi.getValueAt(i, 3).toString());
        
        // Mengisi data kategori ke ComboBox
        cb_kategori.setSelectedItem(tbAspirasi.getValueAt(i, 4).toString());
        
        // KUNCI DISINI: Agar admin tidak bisa mengubah
        cb_kategori.setEnabled(false); 
        
        cb_status.setSelectedItem(tbAspirasi.getValueAt(i, 5).toString());
        
        try {
            java.util.Date date = new java.text.SimpleDateFormat("yyyy-MM-dd").parse(tbAspirasi.getValueAt(i, 6).toString());
            txt_tanggal.setDate(date);
        } catch (Exception e) {
            txt_tanggal.setDate(null);
        }
    }


    }//GEN-LAST:event_tbAspirasiMouseClicked

    private void txt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cariActionPerformed

    private void cb_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_statusActionPerformed

    private void txt_nikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nikActionPerformed

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:                                                                                                                                                                                                                        
    // 1. Bersihkan inputan
    txt_id.setText("");           
    txt_nik.setText("");         
    txt_nama.setText("");         
    txt_tanggal.setDate(null);    
    txt_isi.setText("");          
    cb_status.setSelectedIndex(0); 
    txt_cari.setText("");         

    // 2. Pengaturan Kunci
    txt_nik.setEditable(false); // Admin biasanya tidak boleh edit identitas
    txt_nama.setEditable(false);
    txt_isi.setEditable(false);
    txt_tanggal.setEnabled(false);
    
    // Kategori tetap dikunci (false)
    cb_kategori.setEnabled(false); 

    // 3. Update Tabel (Pastikan kolom kategori ada)
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID"); 
    model.addColumn("NIK / NISN"); 
    model.addColumn("Nama");
    model.addColumn("Isi Aspirasi"); // Sesuaikan urutan dengan tampilkan_data
    model.addColumn("Kategori");
    model.addColumn("Tanggal");
    model.addColumn("Status");
    

    try {
        java.sql.Connection conn = (java.sql.Connection)Koneksi.Koneksi.KoneksiDB();
        String sql = "SELECT * FROM aspirasi ORDER BY id_aspirasi DESC";
        java.sql.ResultSet res = conn.createStatement().executeQuery(sql);
        
        while(res.next()){
            String vNik = res.getString("nik");
            //String vNisn = res.getString("nisn");
            String identitasTampil = res.getString("nik");


            model.addRow(new Object[]{
                res.getString("id_aspirasi"),
                identitasTampil,                   
                res.getString("nama"),        
                res.getString("isi_aspirasi"),
                res.getString("kategori"), // Ambil dari DB
                res.getString("tanggal"),   
                res.getString("status")
                  
            });
        }
        tbAspirasi.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal Refresh: " + e.getMessage());
    }

    }//GEN-LAST:event_btn_refreshActionPerformed

    private void txt_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyReleased
        // TODO add your handling code here:                                  
    cariData(); // Memanggil fungsi pencarian setiap tombol keyboard dilepas
    }//GEN-LAST:event_txt_cariKeyReleased

    private void cb_statusfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_statusfilActionPerformed
        // TODO add your handling code here:
        filterStatus();
        
    }//GEN-LAST:event_cb_statusfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aspirasi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aspirasi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aspirasi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aspirasi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aspirasi1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JComboBox<String> cb_filter;
    private javax.swing.JComboBox<String> cb_kategori;
    private javax.swing.JComboBox<String> cb_status;
    private javax.swing.JComboBox<String> cb_statusfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbAspirasi;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextArea txt_isi;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nik;
    private com.toedter.calendar.JDateChooser txt_tanggal;
    // End of variables declaration//GEN-END:variables
  private void tampilkan_data() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID");              
    model.addColumn("NIK / NISN");
    model.addColumn("Nama");           
    model.addColumn("Isi Aspirasi");   
    model.addColumn("Kategori"); // <--- Tambah Kolom Baru
    model.addColumn("Tanggal"); 
    model.addColumn("Status");         
    

    try {
        java.sql.Connection conn = (java.sql.Connection)Koneksi.Koneksi.KoneksiDB();
        String sql = "SELECT * FROM aspirasi ORDER BY tanggal ASC";
        java.sql.ResultSet res = conn.createStatement().executeQuery(sql);
        
        while(res.next()){
            String nik = res.getString("nik");
           /// String nisn = res.getString("nisn");
            String identitasTampil = res.getString("nik");


            model.addRow(new Object[]{
                res.getString("id_aspirasi"),
                identitasTampil,
                res.getString("nama"), 
                res.getString("isi_aspirasi"),
                res.getString("kategori"), // <--- Ambil data kategori
                res.getString("tanggal"),
                res.getString("status")
                 
            });
        }
        tbAspirasi.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal Tampil: " + e.getMessage());
    }
}
  
  
 private void cariData() {
    DefaultTableModel model = new DefaultTableModel();
    // 1. Tata letak kolom konsisten
    model.addColumn("ID");              // 0
    model.addColumn("NIK / NISN");      // 1
    model.addColumn("Nama");            // 2
    model.addColumn("Isi Aspirasi");    // 3
    model.addColumn("Kategori");        // 4
    model.addColumn("Tanggal");         // 5
    model.addColumn("Status");          // 6
    

    try {
        java.sql.Connection conn = (java.sql.Connection)Koneksi.Koneksi.KoneksiDB();
        String cari = txt_cari.getText();
        String filter = cb_filter.getSelectedItem().toString();
        String sql = "";

        // 2. Logika Query SQL (Tetap sama)
        if (filter.equals("ID")) {
            sql = "SELECT * FROM aspirasi WHERE id_aspirasi LIKE ?";
        } else if (filter.equals("NIK")) {
            sql = "SELECT * FROM aspirasi WHERE nik LIKE ?";
        } else if (filter.equals("Nama")) {
            sql = "SELECT * FROM aspirasi WHERE nama LIKE ?"; 
        } else if (filter.equals("Kategori")) {
            sql = "SELECT * FROM aspirasi WHERE kategori LIKE ?";
        } else {
            // Pencarian Umum (Semua kolom dicari dari depan)
            sql = "SELECT * FROM aspirasi WHERE nama LIKE ? OR nik LIKE ? OR kategori LIKE ?";
        }
        
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        
        // 3. SEMUA menerapkan pencarian dari DEPAN (Tanpa tanda % di awal)
        if (filter.equals("Nama") || filter.equals("ID") || filter.equals("NIK") || filter.equals("Kategori")) {
            pst.setString(1, cari + "%"); 
        } else {
            // Untuk pencarian "Semua" - semua parameter diset cari + "%"
            pst.setString(1, cari + "%"); // nama
            pst.setString(2, cari + "%"); // nik
           // pst.setString(3, cari + "%"); // nisn
            pst.setString(3, cari + "%"); // kategori
        }

        java.sql.ResultSet res = pst.executeQuery();
        
        while(res.next()){
            String vNik = res.getString("nik");
           // String vNisn = res.getString("nisn");
           String identitasTampil = res.getString("nik");


            model.addRow(new Object[]{
                res.getString("id_aspirasi"),
                identitasTampil,
                res.getString("nama"),
                res.getString("isi_aspirasi"),
                res.getString("kategori"), // Tetap rapi di index 4
                res.getString("tanggal"),
                res.getString("status")
            });
        }
        tbAspirasi.setModel(model);
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal Mencari: " + e.getMessage());
    }
}


 
private void filterStatus() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID");
    model.addColumn("NIK / NISN");
    model.addColumn("Nama");
    model.addColumn("Isi Aspirasi");
    model.addColumn("Kategori");
    model.addColumn("Tanggal");
    model.addColumn("Status");
    

   // .trim() akan menghapus spasi di depan atau di belakang teks
String statusPilihan = cb_statusfil.getSelectedItem().toString().trim(); 

try {
    java.sql.Connection conn = (java.sql.Connection)Koneksi.Koneksi.KoneksiDB();
    
    // Gunakan query ini agar lebih aman dari spasi tersembunyi
    String sql = "SELECT * FROM aspirasi WHERE status = ? ORDER BY tanggal DESC";
    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    pst.setString(1, statusPilihan); 
    
    java.sql.ResultSet res = pst.executeQuery();
   
        
        boolean dataDitemukan = false;
        while(res.next()){
            dataDitemukan = true;
            String vNik = res.getString("nik");
          //  String vNisn = res.getString("nisn");
            String identitasTampil = res.getString("nik");


            model.addRow(new Object[]{
                res.getString("id_aspirasi"),
                identitasTampil,
                res.getString("nama"),
                res.getString("isi_aspirasi"),
                res.getString("kategori"), 
                res.getString("tanggal"),
                res.getString("status")
                
            });
        }
        tbAspirasi.setModel(model);

        if (!dataDitemukan) {
            System.out.println("Data dengan status " + statusPilihan + " tidak ditemukan di DB.");
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal menyaring status: " + e.getMessage());
    }
}
   
    public void cetakStruk(String idAspirasi) {
    // Tambahkan WHERE id_aspirasi = ? di akhir query
    String sql = "SELECT\n" +
"     aspirasi.`id_aspirasi` AS aspirasi_id_aspirasi,\n" +
"     aspirasi.`nik` AS aspirasi_nik,\n" +
"     aspirasi.`nama` AS aspirasi_nama,\n" +
"     aspirasi.`isi_aspirasi` AS aspirasi_isi_aspirasi,\n" +
"     aspirasi.`status` AS aspirasi_status,\n" +
"     aspirasi.`tanggal` AS aspirasi_tanggal\n" + // Baris feedback/tanggapan dihapus
"FROM\n" +
"     `aspirasi` aspirasi\n" +
"WHERE aspirasi.`id_aspirasi` = ?";
    
    Connection connection = null;
    PreparedStatement pst = null;
    ResultSet rp = null;
    
    try {
        // Gunakan koneksi yang sudah kamu buat agar konsisten
        connection = (java.sql.Connection)Koneksi.Koneksi.KoneksiDB();
        
        pst = connection.prepareStatement(sql, 
        ResultSet.TYPE_SCROLL_INSENSITIVE, 
        ResultSet.CONCUR_READ_ONLY);
        pst.setString(1, idAspirasi); // Memasukkan ID ke tanda tanya (?)
        rp = pst.executeQuery();
        
        if (rp.next()) { // Cek apakah data ada
            // Reset ResultSet ke awal sebelum dikirim ke Jasper
            rp.beforeFirst(); 
            
            JRResultSetDataSource jrRS = new JRResultSetDataSource(rp);
            // Pastikan path file .jrxml benar
            JasperReport jasperReport = JasperCompileManager.compileReport("G:\\UKKAspirasi\\src\\ReportUKK\\laporan_id.jrxml");
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, jrRS);
            
            JRViewer aViewer = new JRViewer(jasperPrint);
            JDialog viewer = new JDialog();
            viewer.setTitle("Laporan Aspirasi");
            viewer.setAlwaysOnTop(true);
            viewer.getContentPane().add(aViewer);
            
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            viewer.setBounds(0, 0, screenSize.width, screenSize.height);
            viewer.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan di database.");
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error Cetak: " + e.getMessage());
        e.printStackTrace();
    } finally {
        // Resource closing ditangani agar tidak bocor memory
        try { if (rp != null) rp.close(); } catch (Exception e) {}
        try { if (pst != null) pst.close(); } catch (Exception e) {}
    }
}

   private void bersih() {
    txt_id.setText("");           
    txt_nik.setText("");         
    txt_nama.setText("");         
    txt_tanggal.setDate(null);    
    txt_isi.setText("");          
    cb_status.setSelectedIndex(0); 
    
    // Kunci field teks agar tidak bisa diketik
    txt_id.setEditable(false);
    txt_nik.setEditable(false);
    txt_nama.setEditable(false);
    txt_isi.setEditable(false);
    txt_tanggal.setEnabled(false);
}

    private void setTanggalHariIni() {
    txt_tanggal.setDate(new Date());
    txt_tanggal.getDateEditor().setEnabled(false);
    txt_tanggal.getCalendarButton().setEnabled(false);
}
}
